title: Sirri Neba Nforsoh # your name (or website title) here
logo: "/images/Sirri.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in the univeristy of rhode island... 
  <br><br>
  Department of civil and environmental engineering...
  <br><br>
  <a href="https://www.linkedin.com/feed/?trk=onboarding-landing">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
